import {Router,json} from 'express';
import {randomUUID,createHash,createHmac} from 'node:crypto';
import {HttpError,uuid,limit,timestamp} from './http-input.js';

const allowed=(body,keys)=>{if(!body||typeof body!=='object'||Array.isArray(body)||Object.keys(body).some(k=>!keys.includes(k)))throw new HttpError(400,'invalid_body');};
const text=(v,n=120)=>{if(typeof v!=='string'||!v.trim()||v.length>n)throw new HttpError(400,'invalid_text');return v.trim();};
const version=v=>{if(!Number.isInteger(v)||v<1)throw new HttpError(400,'invalid_row_version');return v;};
const reason=v=>text(v,500);
const fingerprint=v=>createHash('sha256').update(v).digest('hex');

export function masterApi(pool,{csrf,idempotencySecret}={}){
 if(typeof idempotencySecret!=='string'||idempotencySecret.length<32)throw new Error('Idempotency secret belum tersedia');
 const r=Router();r.use(json({limit:'8kb'}));
 r.use((req,_res,next)=>req.user?.role==='owner'?next():next(new HttpError(403,'owner_required')));
 const mutate=(req,res,next)=>{
  if(!csrf)return next(new HttpError(503,'csrf_unavailable'));
  csrf(req,res,error=>{
   if(error)return next(error);
   const key=req.get('idempotency-key');
   if(typeof key!=='string'||!urnUuid.test(key))return next(new HttpError(400,'idempotency_key_required'));
   req.ownerIdempotencyKey=key.toLowerCase();next();
  });
 };
 const urnUuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
 const digest=(owner,key,method,path,body)=>createHmac('sha256',idempotencySecret).update(JSON.stringify([owner,key,method,path,body])).digest('hex');
 const invitationToken=(owner,key)=>createHmac('sha256',idempotencySecret).update(`owner-invitation-v1:${owner}:${key}`).digest('base64url');
 async function tx(req,action){
  const db=await pool.connect(),key=req.ownerIdempotencyKey,owner=req.user.id;
  if(!key){db.release();throw new HttpError(400,'idempotency_key_required');}
  const hash=digest(owner,key,req.method,req.originalUrl,req.body);
  try{
   await db.query('BEGIN');
   const locked=(await db.query('SELECT pg_try_advisory_xact_lock(hashtextextended($1,0)) AS acquired',[`${owner}:${key}`])).rows[0].acquired;
   if(!locked)throw new HttpError(409,'idempotency_in_progress');
   const prior=(await db.query('SELECT request_sha256,response_data FROM owner_idempotency WHERE owner_id=$1 AND request_key=$2',[owner,key])).rows[0];
   if(prior){
    if(prior.request_sha256!==hash)throw new HttpError(409,'idempotency_key_conflict');
    await db.query('COMMIT');
    return req.path==='/owner/tenants/invitations' ? {...prior.response_data,token:invitationToken(owner,key)} : prior.response_data;
   }
   const out=await action(db);
   const safe=req.path==='/owner/tenants/invitations' ? {...out,token:undefined} : out;
   await db.query('INSERT INTO owner_idempotency(owner_id,request_key,request_sha256,response_data) VALUES($1,$2,$3,$4)',[owner,key,hash,safe]);
   await db.query('COMMIT');return out;
  }catch(e){await db.query('ROLLBACK').catch(()=>{});throw e;}finally{db.release();}
 }
 async function property(db,owner,id){const q=await db.query('SELECT * FROM properties WHERE id=$1 AND owner_id=$2 FOR SHARE',[uuid(id),owner]);if(!q.rowCount)throw new HttpError(404,'property_not_found');return q.rows[0];}
 async function owned(db,table,id,owner,lock='FOR UPDATE'){const q=await db.query(`SELECT x.* FROM ${table} x JOIN properties p ON p.id=x.property_id WHERE x.id=$1 AND p.owner_id=$2 ${lock}`,[uuid(id),owner]);if(!q.rowCount)throw new HttpError(404,'master_not_found');return q.rows[0];}
 async function audit(db,req,pid,action,type,id,before,after,why){await db.query(`INSERT INTO audit_logs(property_id,actor_user_id,request_id,action,entity_type,entity_id,before_data,after_data,reason) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[pid,req.user.id,randomUUID(),action,type,String(id),before,after,why]);}
 const list={rooms:'rooms',facilities:'communal_loads',devices:'devices','meter-assets':'meter_assets','meter-installations':'meters',readers:'rfid_readers'};
 for(const [path,table] of Object.entries(list))r.get(`/owner/${path}`,async(req,res)=>{const size=limit(req.query.limit,100),after=req.query.after?uuid(req.query.after):null;const q=await pool.query(`SELECT x.* FROM ${table} x JOIN properties p ON p.id=x.property_id WHERE p.owner_id=$1 AND ($2::uuid IS NULL OR x.id>$2) ORDER BY x.id LIMIT $3`,[req.user.id,after,size+1]);res.json({data:q.rows.slice(0,size),next_after:q.rows.length>size?q.rows[size-1].id:null});});
 r.get('/owner/tenants',async(req,res)=>{const q=await pool.query(`SELECT pt.*,u.name,u.email,u.is_active FROM property_tenants pt JOIN properties p ON p.id=pt.property_id JOIN users u ON u.id=pt.user_id WHERE p.owner_id=$1 ORDER BY pt.created_at,pt.id`,[req.user.id]);res.json({data:q.rows});});
 r.get('/owner/occupancies',async(req,res)=>{const q=await pool.query(`SELECT o.* FROM occupancies o JOIN rooms rm ON rm.id=o.room_id JOIN properties p ON p.id=rm.property_id WHERE p.owner_id=$1 ORDER BY o.starts_at,o.id`,[req.user.id]);res.json({data:q.rows});});
 r.get('/owner/rfid-cards',async(req,res)=>{const q=await pool.query(`SELECT c.id,c.user_id,c.label,c.registered_at,c.revoked_at,c.source,c.row_version,c.updated_at FROM rfid_cards c JOIN property_tenants pt ON pt.user_id=c.user_id JOIN properties p ON p.id=pt.property_id WHERE p.owner_id=$1 ORDER BY c.registered_at,c.id`,[req.user.id]);res.json({data:q.rows});});

 r.post('/owner/rooms',mutate,async(req,res)=>{allowed(req.body,['property_id','code','name','active_from','reason']);const out=await tx(req,async db=>{const p=await property(db,req.user.id,req.body.property_id),id=randomUUID();await db.query('INSERT INTO rooms(id,property_id,code,name,active_from) VALUES($1,$2,$3,$4,$5)',[id,p.id,text(req.body.code,32),text(req.body.name),timestamp(req.body.active_from)]);const row=(await db.query('SELECT * FROM rooms WHERE id=$1',[id])).rows[0];await audit(db,req,p.id,'create','room',id,null,row,reason(req.body.reason));return row;});res.status(201).json({data:out});});
 r.patch('/owner/rooms/:id',mutate,async(req,res)=>{allowed(req.body,['name','row_version','reason']);const out=await tx(req,async db=>{const old=await owned(db,'rooms',req.params.id,req.user.id);if(old.source==='simulation')throw new HttpError(409,'simulation_read_only');const q=await db.query('UPDATE rooms SET name=$2,row_version=row_version+1,updated_at=now() WHERE id=$1 AND row_version=$3 RETURNING *',[old.id,text(req.body.name),version(req.body.row_version)]);if(!q.rowCount)throw new HttpError(409,'stale_version');await audit(db,req,old.property_id,'update','room',old.id,old,q.rows[0],reason(req.body.reason));return q.rows[0];});res.json({data:out});});

 const createSimple={facilities:{table:'communal_loads',keys:['property_id','name','load_type','reason'],sql:'INSERT INTO communal_loads(id,property_id,name,load_type) VALUES($1,$2,$3,$4)',args:b=>[text(b.name),['shared','attributable'].includes(b.load_type)?b.load_type:(()=>{throw new HttpError(400,'invalid_load_type')})()]},devices:{table:'devices',keys:['property_id','device_uid','display_name','reason'],sql:"INSERT INTO devices(id,property_id,device_uid,display_name,status) VALUES($1,$2,$3,$4,'active')",args:b=>[text(b.device_uid,80),text(b.display_name)]},'meter-assets':{table:'meter_assets',keys:['property_id','serial_number','label','model','reason'],sql:'INSERT INTO meter_assets(id,property_id,serial_number,label,model) VALUES($1,$2,$3,$4,$5)',args:b=>[b.serial_number?text(b.serial_number,100):null,text(b.label),b.model?text(b.model,100):null]}};
 for(const [path,c] of Object.entries(createSimple))r.post(`/owner/${path}`,mutate,async(req,res)=>{allowed(req.body,c.keys);const out=await tx(req,async db=>{const p=await property(db,req.user.id,req.body.property_id),id=randomUUID();await db.query(c.sql,[id,p.id,...c.args(req.body)]);const row=(await db.query(`SELECT * FROM ${c.table} WHERE id=$1`,[id])).rows[0];await audit(db,req,p.id,'create',c.table,id,null,row,reason(req.body.reason));return row;});res.status(201).json({data:out});});

 r.post('/owner/meter-installations',mutate,async(req,res)=>{allowed(req.body,['meter_asset_id','device_id','kind','room_id','communal_load_id','channel_no','installed_at','reason']);const out=await tx(req,async db=>{const asset=await owned(db,'meter_assets',req.body.meter_asset_id,req.user.id);if(asset.source==='simulation')throw new HttpError(409,'simulation_read_only');const dev=await owned(db,'devices',req.body.device_id,req.user.id);if(dev.property_id!==asset.property_id)throw new HttpError(400,'property_mismatch');const kind=req.body.kind;if(!['main','room','communal'].includes(kind)||!Number.isInteger(req.body.channel_no)||req.body.channel_no<0)throw new HttpError(400,'invalid_installation');const id=randomUUID();await db.query(`INSERT INTO meters(id,property_id,meter_asset_id,device_id,room_id,communal_load_id,kind,channel_no,installed_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[id,asset.property_id,asset.id,dev.id,req.body.room_id?uuid(req.body.room_id):null,req.body.communal_load_id?uuid(req.body.communal_load_id):null,kind,req.body.channel_no,timestamp(req.body.installed_at)]);const row=(await db.query('SELECT * FROM meters WHERE id=$1',[id])).rows[0];await audit(db,req,asset.property_id,'install','meter_installation',id,null,row,reason(req.body.reason));return row;});res.status(201).json({data:out});});
 async function retire(req,res,table,column='retired_at'){const out=await tx(req,async db=>{const old=await owned(db,table,req.params.id,req.user.id);if(old.source==='simulation')throw new HttpError(409,'simulation_read_only');version(req.body.row_version);const at=timestamp(req.body.effective_at),q=await db.query(`UPDATE ${table} SET ${column}=$2,row_version=row_version+1,updated_at=now() WHERE id=$1 AND row_version=$3 RETURNING *`,[old.id,at,req.body.row_version]);if(!q.rowCount)throw new HttpError(409,'stale_version');await audit(db,req,old.property_id,'retire',table,old.id,old,q.rows[0],reason(req.body.reason));return q.rows[0];});res.json({data:out});}
 r.post('/owner/meter-installations/:id/retire',mutate,(req,res)=>{allowed(req.body,['effective_at','row_version','reason']);return retire(req,res,'meters');});
 r.post('/owner/meter-installations/:id/move',mutate,async(req,res)=>{allowed(req.body,['device_id','kind','room_id','communal_load_id','channel_no','effective_at','row_version','reason']);const out=await tx(req,async db=>{const old=await owned(db,'meters',req.params.id,req.user.id);if(old.source==='simulation')throw new HttpError(409,'simulation_read_only');const at=timestamp(req.body.effective_at),why=reason(req.body.reason);const closed=await db.query('UPDATE meters SET retired_at=$2,row_version=row_version+1,updated_at=now() WHERE id=$1 AND row_version=$3 RETURNING *',[old.id,at,version(req.body.row_version)]);if(!closed.rowCount)throw new HttpError(409,'stale_version');const id=randomUUID();await db.query(`INSERT INTO meters(id,property_id,meter_asset_id,device_id,room_id,communal_load_id,kind,channel_no,installed_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[id,old.property_id,old.meter_asset_id,uuid(req.body.device_id),req.body.room_id?uuid(req.body.room_id):null,req.body.communal_load_id?uuid(req.body.communal_load_id):null,req.body.kind,req.body.channel_no,at]);const next=(await db.query('SELECT * FROM meters WHERE id=$1',[id])).rows[0];await audit(db,req,old.property_id,'move_out','meter_installation',old.id,old,closed.rows[0],why);await audit(db,req,old.property_id,'move_in','meter_installation',id,null,next,why);return{previous:closed.rows[0],current:next};});res.json({data:out});});
 r.post('/owner/readers',mutate,async(req,res)=>{allowed(req.body,['property_id','device_id','reader_channel','facility_id','active_from','reason']);const out=await tx(req,async db=>{const p=await property(db,req.user.id,req.body.property_id),id=randomUUID();await db.query('INSERT INTO rfid_readers(id,property_id,device_id,reader_channel,communal_load_id,active_from) VALUES($1,$2,$3,$4,$5,$6)',[id,p.id,uuid(req.body.device_id),req.body.reader_channel,uuid(req.body.facility_id),timestamp(req.body.active_from)]);const row=(await db.query('SELECT * FROM rfid_readers WHERE id=$1',[id])).rows[0];await audit(db,req,p.id,'create','rfid_reader',id,null,row,reason(req.body.reason));return row;});res.status(201).json({data:out});});
 r.post('/owner/readers/:id/retire',mutate,(req,res)=>{allowed(req.body,['effective_at','row_version','reason']);return retire(req,res,'rfid_readers','active_until');});

 r.post('/owner/rfid-cards',mutate,async(req,res)=>{allowed(req.body,['property_id','tenant_id','uid','label','registered_at','reason']);const out=await tx(req,async db=>{const p=await property(db,req.user.id,req.body.property_id),tenant=uuid(req.body.tenant_id);if(!(await db.query("SELECT 1 FROM property_tenants WHERE property_id=$1 AND user_id=$2 AND status='active'",[p.id,tenant])).rowCount)throw new HttpError(400,'active_membership_required');const uid=text(req.body.uid,20).toUpperCase();if(!/^([0-9A-F]{8}|[0-9A-F]{14}|[0-9A-F]{20})$/.test(uid))throw new HttpError(400,'invalid_card_uid');const id=randomUUID();await db.query('INSERT INTO rfid_cards(id,user_id,uid,label,registered_at) VALUES($1,$2,$3,$4,$5)',[id,tenant,uid,text(req.body.label,100),timestamp(req.body.registered_at)]);const row=(await db.query('SELECT id,user_id,label,registered_at,revoked_at,source,row_version,updated_at FROM rfid_cards WHERE id=$1',[id])).rows[0];await audit(db,req,p.id,'create','rfid_card',id,null,{...row,uid_fingerprint:fingerprint(uid)},reason(req.body.reason));return row;});res.status(201).json({data:out});});
 r.post('/owner/rfid-cards/:id/revoke',mutate,async(req,res)=>{allowed(req.body,['property_id','effective_at','row_version','reason']);const out=await tx(req,async db=>{const p=await property(db,req.user.id,req.body.property_id),old=(await db.query(`SELECT c.* FROM rfid_cards c JOIN property_tenants pt ON pt.user_id=c.user_id WHERE c.id=$1 AND pt.property_id=$2 FOR UPDATE OF c`,[uuid(req.params.id),p.id])).rows[0];if(!old)throw new HttpError(404,'card_not_found');if(old.source==='simulation')throw new HttpError(409,'simulation_read_only');if((await db.query('SELECT 1 FROM usage_sessions s JOIN session_participants sp ON sp.usage_session_id=s.id WHERE sp.rfid_card_id=$1 AND s.ended_at IS NULL',[old.id])).rowCount)throw new HttpError(409,'open_session_blocks_revocation');const q=await db.query('UPDATE rfid_cards SET revoked_at=$2,row_version=row_version+1,updated_at=now() WHERE id=$1 AND row_version=$3 RETURNING id,user_id,label,registered_at,revoked_at,source,row_version,updated_at',[old.id,timestamp(req.body.effective_at),version(req.body.row_version)]);if(!q.rowCount)throw new HttpError(409,'stale_version');await audit(db,req,p.id,'revoke','rfid_card',old.id,{id:old.id,revoked_at:old.revoked_at},q.rows[0],reason(req.body.reason));return q.rows[0];});res.json({data:out});});
 r.post('/owner/rfid-cards/:id/replace',mutate,async(req,res)=>{allowed(req.body,['property_id','uid','label','effective_at','row_version','reason']);const out=await tx(req,async db=>{const p=await property(db,req.user.id,req.body.property_id),old=(await db.query('SELECT c.* FROM rfid_cards c JOIN property_tenants pt ON pt.user_id=c.user_id WHERE c.id=$1 AND pt.property_id=$2 FOR UPDATE OF c',[uuid(req.params.id),p.id])).rows[0];if(!old)throw new HttpError(404,'card_not_found');if(old.source==='simulation')throw new HttpError(409,'simulation_read_only');if((await db.query('SELECT 1 FROM usage_sessions s JOIN session_participants sp ON sp.usage_session_id=s.id WHERE sp.rfid_card_id=$1 AND s.ended_at IS NULL',[old.id])).rowCount)throw new HttpError(409,'open_session_blocks_replacement');const at=timestamp(req.body.effective_at),uid=text(req.body.uid,20).toUpperCase(),why=reason(req.body.reason);if(!/^([0-9A-F]{8}|[0-9A-F]{14}|[0-9A-F]{20})$/.test(uid))throw new HttpError(400,'invalid_card_uid');const closed=await db.query('UPDATE rfid_cards SET revoked_at=$2,row_version=row_version+1,updated_at=now() WHERE id=$1 AND row_version=$3 RETURNING id,user_id,label,registered_at,revoked_at,source,row_version,updated_at',[old.id,at,version(req.body.row_version)]);if(!closed.rowCount)throw new HttpError(409,'stale_version');const id=randomUUID();await db.query('INSERT INTO rfid_cards(id,user_id,uid,label,registered_at) VALUES($1,$2,$3,$4,$5)',[id,old.user_id,uid,text(req.body.label,100),at]);const next=(await db.query('SELECT id,user_id,label,registered_at,revoked_at,source,row_version,updated_at FROM rfid_cards WHERE id=$1',[id])).rows[0];await audit(db,req,p.id,'replace_out','rfid_card',old.id,{id:old.id},closed.rows[0],why);await audit(db,req,p.id,'replace_in','rfid_card',id,null,{...next,uid_fingerprint:fingerprint(uid)},why);return{previous:closed.rows[0],current:next};});res.json({data:out});});

 async function deactivate(req,res,table,statusSql){allowed(req.body,['row_version','reason']);const out=await tx(req,async db=>{const old=await owned(db,table,req.params.id,req.user.id);if(old.source==='simulation')throw new HttpError(409,'simulation_read_only');if(table==='communal_loads'&&(await db.query('SELECT 1 FROM usage_sessions WHERE communal_load_id=$1 AND ended_at IS NULL',[old.id])).rowCount)throw new HttpError(409,'open_session_blocks_deactivation');if(table==='devices'&&(await db.query(`SELECT 1 FROM usage_sessions s JOIN rfid_readers rr ON rr.communal_load_id=s.communal_load_id WHERE rr.device_id=$1 AND s.ended_at IS NULL`,[old.id])).rowCount)throw new HttpError(409,'open_session_blocks_deactivation');const q=await db.query(`UPDATE ${table} SET ${statusSql},row_version=row_version+1,updated_at=now() WHERE id=$1 AND row_version=$2 RETURNING *`,[old.id,version(req.body.row_version)]);if(!q.rowCount)throw new HttpError(409,'stale_version');await audit(db,req,old.property_id,'deactivate',table,old.id,old,q.rows[0],reason(req.body.reason));return q.rows[0];});res.json({data:out});}
 r.post('/owner/facilities/:id/deactivate',mutate,(req,res)=>deactivate(req,res,'communal_loads','is_active=false'));
 r.post('/owner/devices/:id/deactivate',mutate,(req,res)=>deactivate(req,res,'devices',"status='inactive',deactivated_at=now()"));
 r.post('/owner/rooms/:id/deactivate',mutate,(req,res)=>{allowed(req.body,['effective_at','row_version','reason']);return retire(req,res,'rooms','active_until');});
 r.post('/owner/meter-assets/:id/retire',mutate,async(req,res)=>{allowed(req.body,['effective_at','row_version','reason']);const out=await tx(req,async db=>{const old=await owned(db,'meter_assets',req.params.id,req.user.id);if(old.source==='simulation')throw new HttpError(409,'simulation_read_only');if((await db.query('SELECT 1 FROM meters WHERE meter_asset_id=$1 AND retired_at IS NULL',[old.id])).rowCount)throw new HttpError(409,'active_installation_blocks_retirement');const q=await db.query("UPDATE meter_assets SET status='retired',retired_at=$2,row_version=row_version+1,updated_at=now() WHERE id=$1 AND row_version=$3 RETURNING *",[old.id,timestamp(req.body.effective_at),version(req.body.row_version)]);if(!q.rowCount)throw new HttpError(409,'stale_version');await audit(db,req,old.property_id,'retire','meter_asset',old.id,old,q.rows[0],reason(req.body.reason));return q.rows[0];});res.json({data:out});});

 r.post('/owner/tenants/invitations',mutate,async(req,res)=>{allowed(req.body,['property_id','name','email','expires_at','reason']);const raw=invitationToken(req.user.id,req.ownerIdempotencyKey),out=await tx(req,async db=>{const p=await property(db,req.user.id,req.body.property_id),email=text(req.body.email,254).toLowerCase();if((await db.query('SELECT 1 FROM users WHERE email=$1 FOR UPDATE',[email])).rowCount)throw new HttpError(409,'email_unavailable');const u=(await db.query("INSERT INTO users(id,name,email,password_hash,role,is_active) VALUES($1,$2,$3,'scrypt:inactive:invited','tenant',false) RETURNING *",[randomUUID(),text(req.body.name),email])).rows[0];const m=(await db.query("INSERT INTO property_tenants(id,property_id,user_id,status) VALUES($1,$2,$3,'invited') RETURNING *",[randomUUID(),p.id,u.id])).rows[0],id=randomUUID();await db.query('INSERT INTO tenant_invitations(id,property_tenant_id,token_sha256,expires_at) VALUES($1,$2,$3,$4)',[id,m.id,fingerprint(raw),timestamp(req.body.expires_at)]);await audit(db,req,p.id,'invite','tenant',u.id,null,{membership_id:m.id,email},reason(req.body.reason));return{id,token:raw,expires_at:req.body.expires_at};});res.status(201).json({data:out});});
 r.post('/owner/occupancies',mutate,async(req,res)=>{allowed(req.body,['property_id','tenant_id','room_id','starts_at','ends_at','reason']);const out=await tx(req,async db=>{const p=await property(db,req.user.id,req.body.property_id),room=await owned(db,'rooms',req.body.room_id,req.user.id);if(room.source==='simulation')throw new HttpError(409,'simulation_read_only');const member=(await db.query("SELECT * FROM property_tenants WHERE property_id=$1 AND user_id=$2 AND status='active' FOR SHARE",[p.id,uuid(req.body.tenant_id)])).rows[0];if(!member)throw new HttpError(400,'active_membership_required');const id=randomUUID();await db.query('INSERT INTO occupancies(id,user_id,room_id,starts_at,ends_at) VALUES($1,$2,$3,$4,$5)',[id,member.user_id,room.id,timestamp(req.body.starts_at),req.body.ends_at?timestamp(req.body.ends_at):null]);const row=(await db.query('SELECT * FROM occupancies WHERE id=$1',[id])).rows[0];await audit(db,req,p.id,'create','occupancy',id,null,row,reason(req.body.reason));return row;});res.status(201).json({data:out});});
 r.post('/owner/occupancies/:id/move',mutate,async(req,res)=>{allowed(req.body,['target_room_id','effective_at','row_version','reason']);const out=await tx(req,async db=>{const old=(await db.query(`SELECT o.*,rm.property_id FROM occupancies o JOIN rooms rm ON rm.id=o.room_id JOIN properties p ON p.id=rm.property_id WHERE o.id=$1 AND p.owner_id=$2 FOR UPDATE OF o`,[uuid(req.params.id),req.user.id])).rows[0];if(!old)throw new HttpError(404,'occupancy_not_found');if(old.source==='simulation')throw new HttpError(409,'simulation_read_only');const target=await owned(db,'rooms',req.body.target_room_id,req.user.id),at=timestamp(req.body.effective_at);if(target.property_id!==old.property_id)throw new HttpError(400,'cross_property_move_not_allowed');if((await db.query('SELECT 1 FROM usage_sessions s JOIN session_participants sp ON sp.usage_session_id=s.id WHERE sp.occupancy_id=$1 AND s.ended_at IS NULL',[old.id])).rowCount)throw new HttpError(409,'open_session_blocks_move');const q=await db.query('UPDATE occupancies SET ends_at=$2,row_version=row_version+1,updated_at=now() WHERE id=$1 AND row_version=$3 RETURNING *',[old.id,at,version(req.body.row_version)]);if(!q.rowCount)throw new HttpError(409,'stale_version');const id=randomUUID();await db.query('INSERT INTO occupancies(id,user_id,room_id,starts_at) VALUES($1,$2,$3,$4)',[id,old.user_id,target.id,at]);const next=(await db.query('SELECT * FROM occupancies WHERE id=$1',[id])).rows[0],why=reason(req.body.reason);await audit(db,req,old.property_id,'move_out','occupancy',old.id,old,q.rows[0],why);await audit(db,req,old.property_id,'move_in','occupancy',id,null,next,why);return{previous:q.rows[0],current:next};});res.json({data:out});});
 r.post('/owner/occupancies/:id/end',mutate,async(req,res)=>{allowed(req.body,['effective_at','row_version','reason']);const out=await tx(req,async db=>{const old=(await db.query('SELECT o.*,rm.property_id FROM occupancies o JOIN rooms rm ON rm.id=o.room_id JOIN properties p ON p.id=rm.property_id WHERE o.id=$1 AND p.owner_id=$2 FOR UPDATE OF o',[uuid(req.params.id),req.user.id])).rows[0];if(!old)throw new HttpError(404,'occupancy_not_found');if(old.source==='simulation')throw new HttpError(409,'simulation_read_only');if((await db.query('SELECT 1 FROM usage_sessions s JOIN session_participants sp ON sp.usage_session_id=s.id WHERE sp.occupancy_id=$1 AND s.ended_at IS NULL',[old.id])).rowCount)throw new HttpError(409,'open_session_blocks_end');const q=await db.query('UPDATE occupancies SET ends_at=$2,row_version=row_version+1,updated_at=now() WHERE id=$1 AND row_version=$3 RETURNING *',[old.id,timestamp(req.body.effective_at),version(req.body.row_version)]);if(!q.rowCount)throw new HttpError(409,'stale_version');await audit(db,req,old.property_id,'end','occupancy',old.id,old,q.rows[0],reason(req.body.reason));return q.rows[0];});res.json({data:out});});
 return r;
}
