import React,{useEffect,useState} from 'react';
import {AdminForm} from './admin-form.jsx';
import {lifecycle} from './admin-mutations.js';
import {adminSections,loadAdminSection,adminRequest,recordStatus,recordTitle,displayValue} from './admin-data.js';
function AdminContent({user}){
 const [form,setForm]=useState(null);
 const [sectionKey,setSectionKey]=useState('overview'),[data,setData]=useState({}),[errors,setErrors]=useState({}),[loading,setLoading]=useState(true),[reload,setReload]=useState(0),[updated,setUpdated]=useState(null);
 const [query,setQuery]=useState(''),[status,setStatus]=useState(''),[source,setSource]=useState(''),[page,setPage]=useState(1),[size,setSize]=useState(10),[detail,setDetail]=useState(null);
 useEffect(()=>{const c=new AbortController();setLoading(true);setData({});setErrors({});setUpdated(null);setDetail(null);
  Promise.all(adminSections.map(async s=>{try{const rows=await loadAdminSection(s,c.signal,(path,signal)=>adminRequest(path,signal,fetch,user.id));if(!c.signal.aborted)setData(v=>({...v,[s.key]:rows}));}catch(e){if(!c.signal.aborted)setErrors(v=>({...v,[s.key]:e.message}));}})).then(()=>{if(!c.signal.aborted){setLoading(false);setUpdated(new Date().toISOString());}});
  return()=>c.abort();
 },[reload,user.id]);
 const section=adminSections.find(s=>s.key===sectionKey),rows=section?data[section.key]:null;
 const filtered=rows?.filter(r=>(!query||[r.id,...section.fields.map(f=>r[f.key])].some(v=>v!==null&&v!==undefined&&String(v).toLowerCase().includes(query.toLowerCase())))&&(!status||recordStatus(section,r).group===status)&&(!source||r.source===source))||[];
 const pages=Math.max(1,Math.ceil(filtered.length/size)),current=Math.min(page,pages),visible=filtered.slice((current-1)*size,current*size);
 function choose(key){setSectionKey(key);setQuery('');setStatus('');setSource('');setPage(1);setDetail(null);}
 const counts=adminSections.map(s=>({section:s,count:data[s.key]?.length}));
 return <main className="admin-page">
  <header className="page-heading"><div><p className="eyebrow">SMARTBILLING / OWNER</p><h1>Administrasi</h1><p>Data master properti, penghuni, dan perangkat Anda.</p></div><button className="refresh-button" disabled={loading} onClick={()=>setReload(v=>v+1)}>{loading?'Memuat…':'↻ Muat ulang data'}</button></header>
  <aside className="admin-notice"><strong>Perubahan tercatat dan dilindungi idempotensi</strong><p>Setiap aksi meminta alasan. Data simulasi tetap baca-saja. Jika hasil belum pasti, ulangi aksi yang sama dari form yang masih terbuka.</p></aside>
  <nav className="admin-tabs" aria-label="Kategori administrasi"><button aria-pressed={sectionKey==='overview'} onClick={()=>choose('overview')}>Ringkasan</button>{adminSections.map(s=><button key={s.key} aria-pressed={sectionKey===s.key} onClick={()=>choose(s.key)}>{s.name}</button>)}</nav>
  {sectionKey==='overview'?<section aria-label="Ringkasan data master" className="admin-summary">{counts.map(({section:s,count})=><button key={s.key} className="admin-summary-card" onClick={()=>choose(s.key)}><strong>{s.name}</strong><span>{count??(errors[s.key]?'Tidak tersedia':'…')}</span><small>{errors[s.key]||s.note}</small></button>)}</section>:<section className="panel" aria-labelledby="admin-list-title">
   <div className="panel-heading"><div><p className="eyebrow">DATA MASTER</p><h2 id="admin-list-title">{section.name}</h2><p className="admin-description">{section.note}</p></div>{section.key!=='properties'&&<button disabled={loading||Object.keys(errors).length>0} onClick={()=>setForm({action:'create',row:null})}>{section.key==='tenants'?'Invitation tenant':'Tambah '+section.name}</button>}</div>
   <div className="admin-filters"><label>Cari pada daftar yang dimuat<input type="search" value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}} placeholder="Nama atau identitas record"/></label><label>Status<select value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">Semua status</option><option value="active">Aktif</option><option value="inactive">Nonaktif / berakhir</option><option value="scheduled">Terjadwal</option></select></label>{section.key!=='properties'&&<label>Sumber<select value={source} onChange={e=>{setSource(e.target.value);setPage(1);}}><option value="">Semua sumber</option><option value="simulation">Simulasi</option><option value="manual">Manual</option></select></label>}</div>
   <p className="admin-description admin-pad">Pencarian dan pagination tampilan dilakukan pada daftar API yang telah dimuat seluruhnya. {section.unpaged?'API kategori ini belum memiliki pagination server.':'Seluruh halaman API diikuti sebelum daftar ditampilkan.'}</p>
   {errors[section.key]?<p className="error" role="alert">{errors[section.key]} <button onClick={()=>setReload(v=>v+1)}>Coba lagi</button></p>:!rows?<p className="empty" role="status">Memuat {section.name.toLowerCase()}…</p>:!filtered.length?<p className="empty" role="status">{rows.length?'Tidak ada data sesuai pencarian atau filter.':'Belum ada data yang dapat diakses pada kategori ini.'}</p>:<div className="admin-table-wrap"><table className="admin-table"><caption className="sr-only">Daftar {section.name}</caption><thead><tr><th scope="col">Record</th><th scope="col">Status</th><th scope="col">Sumber</th><th scope="col">Versi</th><th scope="col">Detail</th></tr></thead><tbody>{visible.map(row=>{const state=recordStatus(section,row),relatedProperty=data.properties?.find(p=>p.id===row.property_id);return <tr key={row.id}><td data-label="Record"><strong>{recordTitle(section,row)}</strong><small>{section.key==='properties'?row.timezone:row.property_id?`Properti · ${relatedProperty?.name||'nama belum tersedia'}`:`ID · …${row.id.slice(-8)}`}</small></td><td data-label="Status"><span className={`pill ${state.group==='active'?'green':'amber'}`}>{state.label}</span>{section.key==='tenants'&&<small>Akun: {row.is_active?'Aktif':'Belum aktif'}</small>}</td><td data-label="Sumber">{section.key==='properties'?'Properti':row.source==='simulation'?<span className="simulation-badge">Simulasi · baca-saja</span>:'Manual'}</td><td data-label="Versi">{row.row_version??'Tidak tersedia'}</td><td data-label="Detail"><button onClick={()=>setDetail(row)}>Lihat detail<span className="sr-only"> {recordTitle(section,row)}</span></button></td></tr>;})}</tbody></table></div>}
   <nav className="admin-pagination" aria-label="Pagination administrasi"><label>Baris per halaman<select value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1);}}>{[10,25,50].map(n=><option key={n}>{n}</option>)}</select></label><span aria-live="polite">{rows?`${filtered.length} record · Halaman ${current} dari ${pages}`:'Belum tersedia'}</span><button disabled={current<=1||!rows} onClick={()=>setPage(current-1)}>Sebelumnya</button><button disabled={current>=pages||!rows} onClick={()=>setPage(current+1)}>Berikutnya</button></nav>
   <div className="panel-foot">Aksi yang didukung API: {section.actions}. {section.key==='rooms'?'Edit hanya mendukung nama kamar.':'Tidak ada edit umum untuk kategori ini.'}</div>
  </section>}
  {detail&&section&&<section className="panel admin-detail" aria-labelledby="admin-detail-title"><div className="panel-heading"><div><p className="eyebrow">DETAIL RECORD</p><h2 id="admin-detail-title">{recordTitle(section,detail)}</h2></div><button onClick={()=>setDetail(null)}>Tutup detail</button></div><p className="admin-description admin-pad">Detail berasal dari respons daftar API; bukan endpoint detail terpisah. Muat ulang data untuk membaca versi terbaru.</p><div className="admin-record-actions">{detail.source!=='simulation'&&lifecycle[section.key].map(([action,label])=><button key={action} disabled={loading||!detail.row_version||Object.keys(errors).length>0} onClick={()=>setForm({action,row:detail})}>{label}</button>)}</div><dl>{[...(section.key==='properties'?[]:[{key:'id',label:'ID record'}]),...section.fields,...(section.key==='properties'?[]:[{key:'property_id',label:'ID properti'}]),...(section.key==='properties'?[]:[{key:'row_version',label:'Versi record'}]),{key:'updated_at',label:'Pembaruan',type:'date'}].map(f=><div key={f.key}><dt>{f.label}</dt><dd>{displayValue(detail[f.key],f.type)}</dd></div>)}</dl><p className="panel-foot">{section.key==='properties'?'ID teknis tetap digunakan di backend, tetapi tidak perlu diingat saat mengelola properti. Mengganti nama tidak mengubah histori terkait.':detail.source==='simulation'?'Data simulasi dilindungi oleh API.':'Data manual.'} Tidak ada credential, UID kartu, payload MQTT, atau token invitation yang ditampilkan.</p></section>}
  {form&&section&&<AdminForm section={section} action={form.action} row={form.row} data={data} user={user} onClose={()=>setForm(null)} onSaved={()=>setReload(v=>v+1)}/>}<footer className="admin-footer">{updated?`Selesai memuat: ${displayValue(updated,'date')}`:'Mengambil data API…'} · Hak akses diperiksa backend. {Object.keys(errors).length>0?'Sebagian kategori belum berhasil dimuat.':''}</footer>
 </main>;
}
export function Administration({user}){return user?.role==='owner'?<AdminContent key={user.id} user={user}/>:<main className="admin-page"><h1>Akses tidak tersedia</h1><p>Administrasi hanya untuk owner. Tidak ada data administrasi yang dimuat.</p></main>;}
