import {newAction,sendAction} from './admin-mutations.js';

export const billingStatus={draft:'Pratinjau',review:'Perlu ditinjau',finalized:'Final',superseded:'Digantikan'};
export const paymentLabel=value=>value==='paid'?'Lunas':'Belum dibayar';
export const issueLabels={no_data:'Data belum tersedia',missing_start_boundary:'Batas awal meter tidak tersedia',missing_end_boundary:'Batas akhir meter tidak tersedia',gap_policy_unset:'Ambang jeda produksi belum ditetapkan',gap:'Ada jeda pembacaan',counter_reset:'Counter meter direset',counter_decreased:'Counter meter menurun',ambiguous_timestamp:'Timestamp pembacaan ambigu',invalid_quality:'Kualitas pembacaan tidak valid',tariff_missing:'Tarif belum tersedia',tariff_overlap:'Jadwal tarif bertumpang tindih',occupancy_boundary_missing:'Batas masa tinggal belum lengkap',session_energy_unavailable:'Energi sesi fasilitas belum tersedia',session_crosses_occupancy:'Sesi melintasi perpindahan kamar',session_crosses_period:'Sesi melintasi periode',facility_energy_outside_session:'Ada energi fasilitas di luar sesi RFID',simulation_not_finalizable:'Data simulasi tidak dapat difinalisasi',negative_property_residual:'Rekonsiliasi energi bernilai negatif'};
export const rupiah=value=>value===null||value===undefined?'Perlu ditinjau':new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(value));
export const kwh=value=>value===null||value===undefined?'Perlu ditinjau':`${new Intl.NumberFormat('id-ID',{maximumFractionDigits:9}).format(Number(value))} kWh`;
export const periodDate=value=>value?new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeZone:'Asia/Jakarta'}).format(new Date(value)):'Belum tersedia';
export const reasonLabel=code=>issueLabels[code]||String(code||'data_belum_lengkap').replaceAll('_',' ');
export function periodTone(period){return period.source!=='production'||period.status==='review'?'amber':period.status==='finalized'?'green':'';}
export function propertyOptions(rooms){return [...new Set((rooms||[]).map(r=>r.property_id).filter(Boolean))].sort();}
export function roomTotals(rooms=[]){return rooms.reduce((a,r)=>({energy:r.room_energy_kwh==null?a.energy:a.energy+Number(r.room_energy_kwh),cost:r.total_cost_rp==null?a.cost:a.cost+Number(r.total_cost_rp),complete:a.complete&&r.room_energy_kwh!=null&&r.total_cost_rp!=null}),{energy:0,cost:0,complete:true});}
export function periodSummary(detail){const rooms=detail?.room_bills||[],review=rooms.filter(r=>r.status!=='finalized').length,ready=rooms.length-review;return{rooms:rooms.length,review,preview:detail?.status==='finalized'?0:ready,final:detail?.status==='finalized'?ready:0,total:detail?.total_cost_rp??detail?.preview_total_cost_rp??null};}
export function roomBillStatus(period,room){if(room.status!=='finalized')return{label:'Perlu ditinjau',tone:'amber'};if(period.source!=='production')return{label:'Pratinjau simulasi',tone:'amber'};return period.status==='finalized'?{label:'Final',tone:'green'}:{label:'Preview',tone:''};}
export function tenantForRoom(roomId,period,occupancies=[],tenants=[]){const matches=occupancies.filter(o=>o.room_id===roomId&&Date.parse(o.starts_at)<Date.parse(period.ends_at)&&(!o.ends_at||Date.parse(o.ends_at)>Date.parse(period.starts_at)));if(matches.length===0)return'Owner / tidak dialokasikan';if(matches.length>1)return'Beberapa tenant · perlu ditinjau';const tenant=tenants.find(t=>t.user_id===matches[0].user_id);return tenant?.name||tenant?.email||`Tenant …${matches[0].user_id.slice(-8)}`;}
export function tenantBillRows(periods=[],details={}){return periods.filter(p=>p.status==='finalized').flatMap(p=>(details[p.id]||[]).map(share=>({...share,period_id:p.id,period_starts_at:p.starts_at,period_ends_at:p.ends_at,revision_no:p.revision_no})));}
export function billableEnergy(share){if(share.room_energy_kwh==null||share.attributable_energy_kwh==null)return null;return Number(share.room_energy_kwh)+Number(share.attributable_energy_kwh);}
export function filterPayments(rows,filters){return rows.filter(x=>(!filters.period_id||x.billing_period_id===filters.period_id)&&(!filters.room_id||x.room_id===filters.room_id)&&(!filters.tenant_id||x.tenant_id===filters.tenant_id)&&(!filters.payment_status||x.payment_status===filters.payment_status));}
export async function billingGet(path,signal,accountId,request=fetch){const response=await request(path,{cache:'no-store',credentials:'same-origin',signal:AbortSignal.any([signal,AbortSignal.timeout(15000)]),headers:{'X-Account-ID':accountId}});if(response.status===401&&typeof window!=='undefined')window.dispatchEvent(new Event('session-expired'));let body;try{body=await response.json();}catch{body={};}if(!response.ok)throw new Error(response.status===403?'Akses billing ditolak.':response.status===404?'Data billing tidak ditemukan.':`Permintaan billing gagal (HTTP ${response.status}).`);return body;}
export function billingAction(path,body,accountId){return newAction(path,'POST',body,accountId);}
export async function sendBillingAction(action,signal,request=fetch){return sendAction(action,signal,request);}
