import React,{useEffect,useState} from 'react';
import {Bar,BarChart,CartesianGrid,Legend,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {billingGet,kwh,paymentLabel,periodDate,rupiah} from './billing-data.js';
import {reportCsv,reportQuery} from './reports-data.js';
const initial={period_id:'',from:'',to:'',room_id:'',payment_status:''};
const dateTime=value=>value?new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Jakarta'}).format(new Date(value)):'—';
export function Reports({user}){const [periods,setPeriods]=useState([]),[rooms,setRooms]=useState([]),[filters,setFilters]=useState(initial),[applied,setApplied]=useState(initial),[report,setReport]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{const c=new AbortController();Promise.all([billingGet('/api/owner/billing-periods?limit=100',c.signal,user.id),billingGet('/api/owner/rooms?limit=1000',c.signal,user.id)]).then(([p,r])=>{setPeriods(p.data.filter(x=>x.status==='finalized'));setRooms(r.data);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[user.id]);
 useEffect(()=>{const c=new AbortController();setLoading(true);setError('');const q=reportQuery(applied);billingGet(`/api/owner/reports/billing${q?'?'+q:''}`,c.signal,user.id).then(setReport).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[applied,user.id]);
 const set=(key,value)=>setFilters(v=>({...v,[key]:value})),rows=report?.data||[],summary=report?.summary,roomLabel=id=>rooms.find(x=>x.id===id)?.name||rooms.find(x=>x.id===id)?.code||'Semua';
 function exportNow(){const meta={period:applied.period_id?periods.find(x=>x.id===applied.period_id)?`${periodDate(periods.find(x=>x.id===applied.period_id).starts_at)} — ${periodDate(periods.find(x=>x.id===applied.period_id).ends_at)}`:'Terpilih':'Semua',range:applied.from&&applied.to?`${applied.from} — ${applied.to}`:'Semua',room:applied.room_id?roomLabel(applied.room_id):'Semua',payment:applied.payment_status?paymentLabel(applied.payment_status):'Semua'};const normalized=rows.map(x=>({period:`${periodDate(x.starts_at)} — ${periodDate(x.ends_at)}`,room:x.room_name||x.room_code,tenant:x.tenant_name,energy_kwh:x.energy_kwh,energy_rate_rp_kwh:x.energy_rate_rp_kwh,total_cost_rp:x.total_cost_rp,billing_status:'Final',payment_status:paymentLabel(x.payment_status),paid_at:x.paid_at?dateTime(x.paid_at):''}));const url=URL.createObjectURL(new Blob([reportCsv(normalized,meta)],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`laporan-smartbilling-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url);}
 return <main className="reports-page"><header className="page-heading"><div><p className="eyebrow">SMARTBILLING / OWNER</p><h1>Riwayat dan Laporan</h1><p>Ringkasan penggunaan, tagihan final, dan pembayaran berdasarkan data backend.</p></div><button className="refresh-button" disabled={loading||!rows.length} onClick={exportNow}>Ekspor CSV</button></header>
  <form className="report-filters" onSubmit={e=>{e.preventDefault();if(Boolean(filters.from)!==Boolean(filters.to)){setError('Tanggal mulai dan akhir harus diisi bersama.');return;}if(filters.from&&filters.to&&filters.from>filters.to){setError('Rentang tanggal tidak valid.');return;}setApplied({...filters});}}><label>Periode<select value={filters.period_id} onChange={e=>set('period_id',e.target.value)}><option value="">Semua periode final</option>{periods.map(x=><option key={x.id} value={x.id}>{periodDate(x.starts_at)} — {periodDate(x.ends_at)} · revisi {x.revision_no}</option>)}</select></label><label>Dari<input type="date" value={filters.from} onChange={e=>set('from',e.target.value)}/></label><label>Sampai<input type="date" value={filters.to} onChange={e=>set('to',e.target.value)}/></label><label>Kamar<select value={filters.room_id} onChange={e=>set('room_id',e.target.value)}><option value="">Semua kamar</option>{rooms.map(x=><option key={x.id} value={x.id}>{x.name||x.code}</option>)}</select></label><label>Status pembayaran<select value={filters.payment_status} onChange={e=>set('payment_status',e.target.value)}><option value="">Semua</option><option value="unpaid">Belum dibayar</option><option value="paid">Lunas</option></select></label><button disabled={loading}>Terapkan</button><button type="button" disabled={loading} onClick={()=>{setFilters(initial);setApplied(initial);}}>Reset</button></form>
  {error&&<p className="error" role="alert">{error}</p>}{loading?<p className="empty panel">Memuat laporan dari backend…</p>:!rows.length?<section className="empty panel"><h2>Belum ada tagihan final</h2><p>Data laporan akan muncul setelah owner menghitung dan memfinalisasi periode yang sesuai filter.</p></section>:<><section className="report-summary"><article><span>Total konsumsi</span><strong>{kwh(summary.energy_kwh)}</strong></article><article><span>Total tagihan</span><strong>{rupiah(summary.total_cost_rp)}</strong></article><article><span>Total lunas</span><strong>{rupiah(summary.paid_cost_rp)}</strong></article><article><span>Total tunggakan</span><strong>{rupiah(summary.unpaid_cost_rp)}</strong></article><article><span>Cakupan</span><strong>{summary.room_count} kamar · {summary.tenant_count} tenant</strong></article></section><section className="report-charts"><Chart title="Konsumsi energi per kamar" data={report.by_room} field="energy_kwh" unit="kWh"/><Chart title="Nominal tagihan per kamar" data={report.by_room} field="total_cost_rp" unit="Rupiah"/></section><section className="panel"><div className="panel-heading"><div><p className="eyebrow">RINCIAN FINAL</p><h2>Per kamar dan tenant</h2></div><span>{rows.length} baris</span></div><div className="billing-table-wrap"><table className="billing-table report-table"><thead><tr><th>Periode</th><th>Kamar</th><th>Tenant</th><th>Energi</th><th>Tarif</th><th>Nominal</th><th>Billing</th><th>Pembayaran</th><th>Tanggal bayar</th></tr></thead><tbody>{rows.map(x=><tr key={x.share_id}><td data-label="Periode">{periodDate(x.starts_at)} — {periodDate(x.ends_at)}</td><td data-label="Kamar">{x.room_name||x.room_code}</td><td data-label="Tenant">{x.tenant_name}</td><td data-label="Energi">{kwh(x.energy_kwh)}</td><td data-label="Tarif">{rupiah(x.energy_rate_rp_kwh)} / kWh</td><td data-label="Nominal">{rupiah(x.total_cost_rp)}</td><td data-label="Billing"><span className="pill green">Final</span></td><td data-label="Pembayaran"><span className={`pill ${x.payment_status==='paid'?'green':'amber'}`}>{paymentLabel(x.payment_status)}</span></td><td data-label="Tanggal bayar">{x.paid_at?dateTime(x.paid_at):'—'}</td></tr>)}</tbody></table></div></section></>}</main>}
function Chart({title,data,field,unit}){const rows=data.map(x=>({...x,label:x.room_name||x.room_code,[field]:Number(x[field])}));return <section className="panel report-chart"><div className="panel-heading"><h2>{title}</h2></div><div role="img" aria-label={title}><ResponsiveContainer width="100%" height={280}><BarChart data={rows} margin={{top:5,right:20,left:10,bottom:35}}><CartesianGrid vertical={false} stroke="#e6ece6"/><XAxis dataKey="label" angle={-20} textAnchor="end" height={60}/><YAxis/><Tooltip formatter={value=>[unit==='Rupiah'?rupiah(value):kwh(value),unit]}/><Legend/><Bar dataKey={field} name={unit} fill={field==='energy_kwh'?'#287c61':'#c58b3c'} radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></section>}
